// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: uvhuhuodsfacdsomjnru

class SupabaseConfig {
  static const String supabaseUrl = 'https://uvhuhuodsfacdsomjnru.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aHVodW9kc2ZhY2Rzb21qbnJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNTQxMDIsImV4cCI6MjA3OTYzMDEwMn0.PuUQdR5z7Ho7k77N-njRj3eg-bqk8OORrfJmFFlyqew';
}
